### PR TITLE
OgAccess::userAccessEntity no longer counts neutral access as forbidden

### PR DESCRIPTION
**Pull request by matslats**

### CODE REVIEW

**Comment by amitaibu** [comment]
@matslats can you please give more context / steps to reproduce the problem (so later it can be transformed to automatic tests)?

**Comment by matslats** [comment]
This was resulting in Access denied to user 1 to page user/1/edit

**Comment by pfrenssen** [comment]
I cannot replicate this. My current setup is the following:
- I have a custom group entity called "Collection".
- My User entity is a group content type that belongs to the Collection group.
- I log in as UID1 and visit user/1/edit.

When I step throught the affected part then this line correctly returns `AccessResultAllowed`:

```
          $user_access = static::userAccess($group, $operation, $user);
```

Since in `OgAccess::userAccess()` the access is always allowed for UID 1:

```
    // User ID 1 has all privileges.
    if ($user->id() == 1) {
      return AccessResult::allowed()->addCacheableDependency($cacheable_metadata);
    }
```

@matslats, could you provide some more information on how to replicate this?

**Comment by matslats** [comment]
sorry this isn't happening for me any more.

**Pull request closed without merging**
