### PR TITLE
Delete user memberships when a group is deleted

### LINKED ISSUE #176: Delete memberships when a group is deleted
In PR #162 the group content is cleaned up when a group is deleted. We also need to clean up group memberships when this happens.

Ref `og_entity_predelete()`

### PR DESCRIPTION
**Pull request by pfrenssen**
Here is an implementation for issue #176. We should clean up the memberships of users that are members of a group when the group is deleted.

This depends on PR #162.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Now that #176 is in this is ready for review.

**Comment by amitaibu** [comment]
This on the fly approach might be problematic if we have _lots_ of users.

Why not delegate this deletion to the a `OgDeleteOrphans` plugin?

**Comment by amitaibu** [comment]
(which will also be more consistent with OG7)

**Comment by pfrenssen** [comment]
Note that this will have a minor merge conflict with https://github.com/amitaibu/og/pull/189 - I'll take care of it in case that issue would be merged in first.

**Comment by amitaibu** [comment]
Needs a re-roll :)

**Comment by pfrenssen** [comment]
Rerolled!

**Comment by amitaibu** [comment]
Thanks!

**Pull request merged**
