### PR TITLE
Moving all existing tests to individual classes.

### PR DESCRIPTION
**Pull request by jhedstrom**
- Direct port, none will pass at this time.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Going to work on this. I'll fork this branch and rebase it on the latest 8.x-1.x. I'll do a code review and fix anything that I find.

**Comment by pfrenssen** [comment]
It looks very good. I checked that all classes are correctly ported. All of them are, except two obsolete ones (`OgMigrate7000TestCase` and `OgMigrate7200TestCase`). We don't need them any more.

The tests show up correctly in the Simpletest UI, and they can be started from there, but the test runner hangs. That is out of scope for this issue. When running the tests from the CLI I get correct results, all of them fail, mostly due to missing functions.

Two remarks during the review, both documentation related:
- In Drupal 8 the static `$modules` property no longer exists on the base class and it is not defined on the interface, so we should no longer document it with `@inheritdoc`.
- The docblocks for the classes should use the third person verb in the summary.

**Comment by pfrenssen** [comment]
I forked this PR and fixed my remarks regarding the documentation of the `$modules` property and using the third party verb in the class and method docblocks. Here's the commit in my fork: https://github.com/ec-europa/og/commit/df07b9b4282d92087e6e97bb380744e7cc601d62

@jhedstrom, could you cherry-pick this commit?

**Comment by jhedstrom** [comment]
@pfrenssen done!

**Comment by damiankloip** [comment]
@amitaibu I think we might as well get this in, it just gets a bunch of the moving tests to PSR-4. The tests all still need fixing anyway. This just makes that a bit easier I guess .

**Comment by damiankloip** [comment]
Actually, thinking about this again. Having all tests converted in one go but completely broken will cause havoc with our CI.

**Comment by pfrenssen** [comment]
Shall we put them in a separate group like `@og-wip` for the moment? Then as soon as a test is converted and working we can put it in the `@og` group so it gets verified on CI.

**Comment by amitaibu** [comment]
On one hand I think the `og-wip` is a good idea, and the other it might cause us to miss non-ported tests.

I'm ok with either one.

**Comment by damiankloip** [comment]
Yeah, I would prefer to port one by one for that reason. But this has been done here.....

**Comment by pfrenssen** [comment]
We can always grep for @og-wip, and can create an issue in the queue so this is not forgotten.

I could also make a small script that splits up all individual tests in separate branches, then we can work on each test as needed and this work is not lost.

**Comment by pfrenssen** [comment]
I've split up all the tests into separate branches: https://github.com/ec-europa/og/branches/all

Here is the script I used, in case this needs to be redone for some reason:

```
#!/bin/bash -e

declare -a tests=(
    "OgAccessTest"
    "OgAudienceFieldAccessOverrideTest"
    "OgAudienceFieldAutoCreateTest"
    "OgAutoCompleteAccessibleGroupsValidationTest"
    "OgBehaviorHandlerTest"
    "OgComplexWidgetTest"
    "OgDefaultAccessFieldTest"
    "OgDeleteOrphansTest"
    "OgEntityFieldQueryFieldConditionTest"
    "OgEntityFieldQueryTest"
    "OgGroupAndUngroupTest"
    "OgMetaDataTest"
    "OgNodeAccessTest"
    "OgNonMembersPublishingContentTest"
    "OgPermissionsTest"
    "OgRoleRevokeTest"
    "OgSelectAccessibleGroupsValidationTest"
    "OgUserCanPublishGroupContentTypeOnlyInGroupTest"
)

scaffold_sha=4b436ed733
fullsplit_sha=be7f35ab7a

for test in "${tests[@]}" ; do
    filename="src/Tests/${test}.php"
    git checkout -B $test 4b436ed733
    mkdir -p src/Tests
    git show $fullsplit_sha:$filename > $filename
    git add $filename
    git commit -m "Split $test into a separate class." --author="Jonathan Hedstrom <jhedstrom@gmail.com>"
    git push origin $test
done
```

I made a "test-split-scaffold" branch that serves as the base of the all these branches. It simply removes the old tests. I will make a PR for this now.

**Comment by amitaibu** [comment]
Lets go with one by one. At least for the access related stuff, just so we make sure we are careful with them.

After the API will be in place, we might want to do a bulk update. Sounds ok?

**Comment by pfrenssen** [comment]
Sure! They now all live in my fork, do you think this is discoverable enough for new contributors? It's maybe premature to add PRs for all of them since it will overwhelm the PR overview.

I've added everybody as collaborators on my fork.

**Comment by amitaibu** [comment]
Seems we are expanding the tests even more than we had in D7. Also, since we have some architecture changes the tests don't map one-to-one.

In short, I'll close it.

**Pull request closed without merging**
