### PR TITLE
Move state types to \Drupal\og\ OgMembershipInterface

### PR DESCRIPTION
**Pull request by dawehner**

### CODE REVIEW

**Comment by damiankloip** [comment]
@amitaibu did we start doing this in another PR? or did we just talk about it?

I think we wanted to add an `OgMembershipInterface` and add these to that instead. @dawehner what do you think about that?

**Comment by amitaibu** [comment]
https://github.com/amitaibu/og/pull/64#issuecomment-162304750

**Comment by dawehner** [comment]
Sounds totally reasonable!

**Comment by amitaibu** [comment]
@dawehner are you going to work on it? :)

**Comment by dawehner** [comment]
Sure, let's start now

**Comment by damiankloip** [comment]
This looks good to me.

Me and @dawehner talked about changing the names of the methods on OgMembership, as they are kind of confusing. So I think a couple of follow ups:
- Make OgMembership implement this interface, add other methods, and rename methods/props
- Anywhere that type hints of docs that @return OgMembership should be changed to use the interface

**Comment by amitaibu** [comment]
Follow-up ideas sound good :) Thanks!

**Pull request merged**
