### PR TITLE
Not every entity is fieldable

### PR DESCRIPTION
**Pull request by chx**
This right breaks page manager.

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks. If the entity is not fieldable, we should return early as it can't have group audience attached it.

**Comment by chx** [comment]
Sure. I added a comment too.

**Comment by amitaibu** [comment]
Tests seem red

**Comment by chx** [comment]
I am working on them as fast as I can but got hang up on http://stackoverflow.com/questions/34931201/php-prophecy-mystery

**Comment by chx** [comment]
Let's hope this will be green.

**Comment by chx** [comment]
OK this is really pretty now.

**Comment by amitaibu** [comment]
:+1: Thanks

**Comment by damiankloip** [comment]
Nice. I was going to flag up the original tey/catch version. This one looks great!

**Pull request merged**
