### PR TITLE
Create field refactoring

### PR DESCRIPTION
**Pull request by amitaibu**
I'm opening this PR just so it's easier to review the changes I've added. I'll merge once green, so we can keep work on #20

### CODE REVIEW

**Comment by amitaibu** [comment]
In general you can see there is some work on doing better API handling, for example:
- throwing exceptions instead of silently ignoring them
- Improve the names of the methods to be more descriptive
- consolidating logic, so implementing modules won't have to repeat stuff (e.g. calling `$this->getEntityType()` in the field storage config

**Comment by damiankloip** [comment]
Looks good @amitaibu. One thing. We should consider creating our own exceptions intend of just using Exception.

**Comment by damiankloip** [comment]
*instead. Sorry on mobile :)

**Comment by amitaibu** [comment]
I wasn't sure if wanted to do this for those exceptions, but np.

**Comment by damiankloip** [comment]
Just a thought for discussion more than anything.

**Pull request merged**
