### PR TITLE
Create membership DX followup

### PR DESCRIPTION
**Pull request by pfrenssen**
This is a followup of PR #258 - we can improve DX even harder :D

### CODE REVIEW

**Comment by pfrenssen** [comment]
I also ran PHP CodeSniffer on `OgMembership` and `OgMembershipInterface` and fixed all warnings.

**Comment by pfrenssen** [comment]
This single failure in the last commit was because `OgMembershipReferenceItemList` was creating a new `OgMembership` entity through a dedicated helper function instead of using `OgMembership::create()`.

I have changed it so it is consistent throughout the entire codebase. I've also removed that helper method `Og::membershipStorage()`. I don't think this has much value for a D8 developer, it's only a few characters less to type than `$this->entityTypeManager->getStorage()`, and this is something which everyone immediately recognizes.

**Comment by amitaibu** [comment]
Tiny comment. Rest looks great

**Comment by amitaibu** [comment]
I'll get this one in, after I'll merge #251 (i.e. tomorrow)

**Comment by amitaibu** [comment]
Needs a re-roll (I preferred to get the coder in, as I realized there will most probably be merge conflicts with this one).

**Comment by pfrenssen** [comment]
Rerolled, addressed remark, added some random out of scope documentation fixes :strawberry:

**Comment by amitaibu** [comment]
`phpcbf` should be your friend here :)

**Comment by pfrenssen** [comment]
Hahaha caught red handed!!! Really nice to have this automatically checked now. I'll have a look to fix these during my lunch break.

I'll also make a followup to have this coding standards check available locally as a dev-dependency. Then we can easily run the coding standards check before pushing.

**Comment by amitaibu** [comment]
no worries, I've ran `phpcbf` on your branch and pushed. coder should be fixed now.

**Comment by amitaibu** [comment]
Travis seems to be stuck :/

**Comment by amitaibu** [comment]
Oh, actually it's finally running!

**Comment by amitaibu** [comment]
Thanks!

**Pull request merged**
