### PR TITLE
First try of travis.

### PR DESCRIPTION
**Pull request by RoySegall**

### CODE REVIEW

**Comment by amitaibu** [comment]
Just came across this - https://www.chapterthree.com/blog/drupal-8-automated-testing-travis-ci

Also Rules should have travis running for D8

**Comment by RoySegall** [comment]
I'm taking it from rules. I think minor typos is what casuing the problems.

**Comment by RoySegall** [comment]
@amitaibu Travis is green with @damiankloip lovely unit test. Merge?

**Comment by amitaibu** [comment]
That function name should start with lowercase. After that please merge.

**Pull request closed without merging**
