### PR TITLE
Move OG UI to modules sub directory

### PR DESCRIPTION
**Pull request by RoySegall**
@chx I think will impact your work as well.

### CODE REVIEW

**Comment by chx** [comment]
:( mine should've been merged first.

**Comment by amitaibu** [comment]
In other words, @RoySegall - please review @chx's PR :)

**Comment by RoySegall** [comment]
We are talking about #60, right?

**Comment by amitaibu** [comment]
Yes

**Comment by amitaibu** [comment]
We will get this in after #60

**Comment by damiankloip** [comment]
I also have a lot of work in https://github.com/amitaibu/og/pull/40 that will be affected by this. We can do this move at any time really. So I think wait until it is least disruptive?

**Comment by amitaibu** [comment]
Sure, there's no rush with this PR as it's a trivial one.

**Comment by damiankloip** [comment]
:+1:

**Pull request closed without merging**
