### PR TITLE
Membership reference constraints

### PR DESCRIPTION
**Pull request by pfrenssen**
This a rebased branch containing the fix from PR #135. That PR contained a number of unrelated commits.

### CODE REVIEW

**Comment by pfrenssen** [comment]
OK this is green. I was wondering if the removal of the original constraint validator would break anything. I didn't think it would since it was completely broken, but you never know :)

I'm going to start working on a test that does a full setup through the UI, that includes the ajax callbacks. I'll do this in a separate PR, since it seems that more things are broken when I submit the form after adding a group to the group audience field.

This at least makes it possible to add groups to the group audience field. Thanks @matslats!

**Comment by amitaibu** [comment]
@pfrenssen just to confirm - you mean without this PR you cannot add a group via UI to a group audience field?

**Comment by matslats** [comment]
Should I delete my branch membershipReference-constraints?

**Comment by amitaibu** [comment]
> Should I delete my branch membershipReference-constraints?

You can - this one is now a different branch.

**Comment by pfrenssen** [comment]
@amitaibu, indeed. The ajax callback for adding a group to a group audience field throws a fatal error:

> Error: Call to undefined method Drupal\Core\TypedData\Plugin\DataType\IntegerData::isEmpty() in Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate() (line 78 of core/lib/Drupal/Core/Entity/Plugin/Validation/Constraint/ValidReferenceConstraintValidator.php).

To replicate this the quickest:
1. Create a group type and add at least 1 group.
2. Log in as UID 1.
3. Go to admin/people/create.
4. Start typing the title of your group in the group audience field. The ajax callback will never show any suggestions, since it fails with the error above.

This PR fixes that, but I get another error later on when actually submitting the form. I'm going to write a test that does the necessary steps to add a user to a group through the UI, so that we can see what else might fail.

**Pull request merged**
