### PR TITLE
Utilize Role isAdmin() functionality

### PR DESCRIPTION
**Pull request by amitaibu**
A re-roll of #225 as a branch of this repo

### CODE REVIEW

**Comment by damiankloip** [comment]
@amitaibu :heart:

**Comment by amitaibu** [comment]
Merged, thanks!

**Comment by damiankloip** [comment]
Thanks @amitaibu, you are my hero!

**Comment by amitaibu** [comment]
dude, haven't you seen that _you_ are one of the [heroes](http://www.gizra.com/content/og-message-stack-drupal8/)? :)

**Pull request merged**
