### PR TITLE
Remove tables from hook_schema()

### PR DESCRIPTION
**Pull request by matslats**
I don't know how any body could install the module with og_membership being wrongly defined in hook_schema and overriding the entity baseFieldDefinitions

### CODE REVIEW

**Comment by RoySegall** [comment]
Good idea but I would recommend on remove all the schemas since there is no use for them any more. I did it in #115 but for now that PR is frozen until we have a better solution.

**Comment by pfrenssen** [comment]
Ok so let's remove the whole `hook_schema()` in this issue. No reason to wait for #115 to make this non-disruptive change.

**Comment by amitaibu** [comment]
> but for crying out loud can't somebody just copy and paste my offerings into their branches?

Sorry, but it doesn't work like this. We're willing to guide you through it, but not copy/ paste stuff. I honestly do believe git branches are not something you can't master quickly ;)

**Comment by amitaibu** [comment]
Merged, thanks.

**Comment by matslats** [comment]
Thanks for your willingness. Its not that I'm resistant to learning git
although I do fear the time cost of getting in a tangle, it is the need
to maintain multiple branches while I'm developing something that
depends on groups. So I could do a fix and then not have access to it
until it is committed back to core, and I make a new branch and download
it and reinstall drupal. So its just one at a time for now! OK the next
is coming....

**Comment by amitaibu** [comment]
I think you have the wrong idea about branches ;) They are _literally_ taking less than a sec to create, from one _single_ repo:

``` bash
git checkout 8.x-1.x
git pull

# create a new branch
git checkout -b my-new-brach
git commit -am "commit message"
git push origin my-new-brach

# and again, back to the main branch
git checkout 8.x-1.x
git pull
```

**Comment by matslats** [comment]
Super busy right now. Hopefully I'll be back with several branches in a few days

**Pull request merged**
