### PR TITLE
Get config object from factory in refreshGroupMap, not just instantiation

### PR DESCRIPTION
**Pull request by damiankloip**
This should fix the problem @RoySegall is seeing in tests with latest group config not being available directly after.

### CODE REVIEW

**Comment by damiankloip** [comment]
So I think the problem you are seeing in tests and fixed by https://github.com/amitaibu/og/pull/30 is that refreshGroupMap() only gets the config object again, I think we need to fetch it from the factory again. Then the edits should always be current.

**Comment by RoySegall** [comment]
could be. For now I'll use the fix and test later on today and let you know.

**Comment by RoySegall** [comment]
Worked. 10x again.

**Comment by damiankloip** [comment]
OK. @amitaibu I think this is good to go then.

**Comment by damiankloip** [comment]
No problem, cheers @RoySegall

**Pull request merged**
