### PR TITLE
Use string concatenation instead of FormattableMarkup

### PR DESCRIPTION
**Pull request by amitaibu**
#57

### CODE REVIEW

**Comment by amitaibu** [comment]
@Roysegall as a side not, we should change it in Message as-well ;)

**Comment by dawehner** [comment]
sprintf IMHO is only useful when you have generic replacement functions like t() or format_string(). For exceptions you can improve the readability a bit by simple use inline variables:

```
"foo $bar $baz"
```

vs.

```
sprintf('foo %s %s', $bar, baz)
```

**Comment by amitaibu** [comment]
@dawehner I've seen core use only `sprintf`, without concatenation. Do you have an example from core?

**Comment by dawehner** [comment]
Feel free to choose some from
https://www.drupal.org/files/issues/2514044-38.patch

**Comment by amitaibu** [comment]
:+1: 

I'll change it then.

**Comment by dawehner** [comment]
Cool, thank you

**Comment by damiankloip** [comment]
Yep, either works for me!

**Comment by amitaibu** [comment]
I've made the change and adapted test.

**Comment by dawehner** [comment]
+1

**Pull request merged**
