### PR TITLE
Fix missing or incorrect @file PHPdocs

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
btw, I've also noticed some wrong names e.g. `OgFieldsInterface.php` should be `OgFieldInterface.php` - but I  think we can do it in smaller PRs.

**Comment by amitaibu** [comment]
ready for review.

**Comment by amitaibu** [comment]
@RoySegall ^^

**Comment by RoySegall** [comment]
Look OK to me.

**Pull request merged**
